### ISSUE TITLE
Does it work with UPS_HAT_B as well, the install looks similar...

### ISSUE THREAD

**Issue by confuserated** [mykhailog/hacs_waveshare_ups_hat#10]
Just wondering if you know whether it works with the UPS_HAT_B as well?

https://www.waveshare.com/wiki/UPS_HAT_(B)#Support

If you don't know I'll download the Waveshare code for both and compare.

Regards

**Comment by mykhailog** [comment]
it looks like it should work with UPS_HAT_B.

**Comment by confuserated** [comment]
It does work! Yay!

This is great news for me since the only other UPS I could find that had HASSIO support in any way was the pijuice, and that's too much money for what it is I think.

**Comment by susandehaviland** [comment]
Also works with Waveshare UPS module 3S which is based on pretty much the same architecture, except with three cells and no pogo pin connection, just header pins which need to be joined together.

I had problems with (many) different UPS hat B devices, with power problems on the Pi 4 (red LED goes off intermittently) and these seem more robust so far.

The only changes needed to the Integration is to edit the config files (two altogether) where the address of the I2C device is set at 0x42 which needs to be changed to 0x41 in order to make it work.
